PACKAGE APP; 
IMPORT ORG.APACHE.STRUTS.ACTION.*; 
PUBLIC CLASS REGISTERFORM EXTENDS ACTIONFORM { 
PROTECTED STRING USERNAME; 
PROTECTED STRING PASSWORD1; 
PROTECTED STRING PASSWORD2; 
PUBLIC STRING GETUSERNAME () {RETURN THIS.USERNAME;}; 
PUBLIC STRING GETPASSWORD1() {RETURN THIS.PASSWORD1;}; 
PUBLIC STRING GETPASSWORD2() {RETURN THIS.PASSWORD2;}; 
PUBLIC VOID SETUSERNAME (STRING USERNAME) {THIS.USERNAME = USERNAME;}; 
PUBLIC VOID SETPASSWORD1(STRING PASSWORD) {THIS.PASSWORD1 = PASSWORD;}; 
PUBLIC VOID SETPASSWORD2(STRING PASSWORD) {THIS.PASSWORD2 = PASSWORD;}; 
}